package gestion.trelux.metier;
// Generated 24 mai 2018 11:55:21 by Hibernate Tools 4.3.1



/**
 * DetailsinventaireId generated by hbm2java
 */
public class DetailsinventaireId  implements java.io.Serializable {


     private String idpersonne;
     private String type;
     private String codegerant;
     private String codeinventaire;

    public DetailsinventaireId() {
    }

    public DetailsinventaireId(String idpersonne, String type, String codegerant, String codeinventaire) {
       this.idpersonne = idpersonne;
       this.type = type;
       this.codegerant = codegerant;
       this.codeinventaire = codeinventaire;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCodegerant() {
        return this.codegerant;
    }
    
    public void setCodegerant(String codegerant) {
        this.codegerant = codegerant;
    }
    public String getCodeinventaire() {
        return this.codeinventaire;
    }
    
    public void setCodeinventaire(String codeinventaire) {
        this.codeinventaire = codeinventaire;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsinventaireId) ) return false;
		 DetailsinventaireId castOther = ( DetailsinventaireId ) other; 
         
		 return ( (this.getIdpersonne()==castOther.getIdpersonne()) || ( this.getIdpersonne()!=null && castOther.getIdpersonne()!=null && this.getIdpersonne().equals(castOther.getIdpersonne()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getCodegerant()==castOther.getCodegerant()) || ( this.getCodegerant()!=null && castOther.getCodegerant()!=null && this.getCodegerant().equals(castOther.getCodegerant()) ) )
 && ( (this.getCodeinventaire()==castOther.getCodeinventaire()) || ( this.getCodeinventaire()!=null && castOther.getCodeinventaire()!=null && this.getCodeinventaire().equals(castOther.getCodeinventaire()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonne() == null ? 0 : this.getIdpersonne().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getCodegerant() == null ? 0 : this.getCodegerant().hashCode() );
         result = 37 * result + ( getCodeinventaire() == null ? 0 : this.getCodeinventaire().hashCode() );
         return result;
   }   


}


