package gestion.trelux.metier;
// Generated 24 mai 2018 11:55:21 by Hibernate Tools 4.3.1



/**
 * Detailsinventaire generated by hbm2java
 */
public class Detailsinventaire  implements java.io.Serializable {


     private DetailsinventaireId id;
     private Gerant gerant;
     private Inventaire inventaire;
     private Integer produitperime;
     private Integer produitarisque;

    public Detailsinventaire() {
    }

	
    public Detailsinventaire(DetailsinventaireId id, Gerant gerant, Inventaire inventaire) {
        this.id = id;
        this.gerant = gerant;
        this.inventaire = inventaire;
    }
    public Detailsinventaire(DetailsinventaireId id, Gerant gerant, Inventaire inventaire, Integer produitperime, Integer produitarisque) {
       this.id = id;
       this.gerant = gerant;
       this.inventaire = inventaire;
       this.produitperime = produitperime;
       this.produitarisque = produitarisque;
    }
   
    public DetailsinventaireId getId() {
        return this.id;
    }
    
    public void setId(DetailsinventaireId id) {
        this.id = id;
    }
    public Gerant getGerant() {
        return this.gerant;
    }
    
    public void setGerant(Gerant gerant) {
        this.gerant = gerant;
    }
    public Inventaire getInventaire() {
        return this.inventaire;
    }
    
    public void setInventaire(Inventaire inventaire) {
        this.inventaire = inventaire;
    }
    public Integer getProduitperime() {
        return this.produitperime;
    }
    
    public void setProduitperime(Integer produitperime) {
        this.produitperime = produitperime;
    }
    public Integer getProduitarisque() {
        return this.produitarisque;
    }
    
    public void setProduitarisque(Integer produitarisque) {
        this.produitarisque = produitarisque;
    }




}


