package gestion.trelux.metier;
// Generated 24 mai 2018 11:55:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gerant generated by hbm2java
 */
public class Gerant  implements java.io.Serializable {


     private GerantId id;
     private Boutique boutique;
     private Employe employe;
     private String securegerant;
     private Integer droit;
     private Set detailsinventaires = new HashSet(0);

    public Gerant() {
    }

	
    public Gerant(GerantId id, Employe employe) {
        this.id = id;
        this.employe = employe;
    }
    public Gerant(GerantId id, Boutique boutique, Employe employe, String securegerant, Integer droit, Set detailsinventaires) {
       this.id = id;
       this.boutique = boutique;
       this.employe = employe;
       this.securegerant = securegerant;
       this.droit = droit;
       this.detailsinventaires = detailsinventaires;
    }
   
    public GerantId getId() {
        return this.id;
    }
    
    public void setId(GerantId id) {
        this.id = id;
    }
    public Boutique getBoutique() {
        return this.boutique;
    }
    
    public void setBoutique(Boutique boutique) {
        this.boutique = boutique;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public String getSecuregerant() {
        return this.securegerant;
    }
    
    public void setSecuregerant(String securegerant) {
        this.securegerant = securegerant;
    }
    public Integer getDroit() {
        return this.droit;
    }
    
    public void setDroit(Integer droit) {
        this.droit = droit;
    }
    public Set getDetailsinventaires() {
        return this.detailsinventaires;
    }
    
    public void setDetailsinventaires(Set detailsinventaires) {
        this.detailsinventaires = detailsinventaires;
    }




}


