package gestion.trelux.metier;
// Generated 24 mai 2018 11:55:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inventaire generated by hbm2java
 */
public class Inventaire  implements java.io.Serializable {


     private String codeinventaire;
     private String dateinventaire;
     private Integer quentitevendue;
     private Integer chiffreaffaire;
     private Integer benefice;
     private Integer perte;
     private Set detailsinventaires = new HashSet(0);

    public Inventaire() {
    }

	
    public Inventaire(String codeinventaire) {
        this.codeinventaire = codeinventaire;
    }
    public Inventaire(String codeinventaire, String dateinventaire, Integer quentitevendue, Integer chiffreaffaire, Integer benefice, Integer perte, Set detailsinventaires) {
       this.codeinventaire = codeinventaire;
       this.dateinventaire = dateinventaire;
       this.quentitevendue = quentitevendue;
       this.chiffreaffaire = chiffreaffaire;
       this.benefice = benefice;
       this.perte = perte;
       this.detailsinventaires = detailsinventaires;
    }
   
    public String getCodeinventaire() {
        return this.codeinventaire;
    }
    
    public void setCodeinventaire(String codeinventaire) {
        this.codeinventaire = codeinventaire;
    }
    public String getDateinventaire() {
        return this.dateinventaire;
    }
    
    public void setDateinventaire(String dateinventaire) {
        this.dateinventaire = dateinventaire;
    }
    public Integer getQuentitevendue() {
        return this.quentitevendue;
    }
    
    public void setQuentitevendue(Integer quentitevendue) {
        this.quentitevendue = quentitevendue;
    }
    public Integer getChiffreaffaire() {
        return this.chiffreaffaire;
    }
    
    public void setChiffreaffaire(Integer chiffreaffaire) {
        this.chiffreaffaire = chiffreaffaire;
    }
    public Integer getBenefice() {
        return this.benefice;
    }
    
    public void setBenefice(Integer benefice) {
        this.benefice = benefice;
    }
    public Integer getPerte() {
        return this.perte;
    }
    
    public void setPerte(Integer perte) {
        this.perte = perte;
    }
    public Set getDetailsinventaires() {
        return this.detailsinventaires;
    }
    
    public void setDetailsinventaires(Set detailsinventaires) {
        this.detailsinventaires = detailsinventaires;
    }




}


